### ISSUE TITLE
Set the locale for the packaging system

### ISSUE THREAD

**Issue by imobachgs** [yast/d-installer#334] opened 2022-11-25 09:58 UTC
We need to set the package system locale (calling to `Pkg.SetPackageLocale`) in the software service before starting the installation. Remember that the locale settings are in the *language* service now.

It is related to #274.

**Comment by mchf** [comment] 2023-03-13 09:37
#274 was closed as "cannot reproduce anymore", so closing even this one.

**Closed by mchf** 2023-03-13 09:37 UTC
Labels: bug, good first issue
