### ISSUE TITLE
set locale LC_*: cannot change locale (cs_CZ.UTF-8): No such file or directory

### ISSUE THREAD

**Issue by lkocman** [yast/d-installer#274] opened 2022-10-26 14:28 UTC
I expect this to be a known issue with the team, but wanted to have a tracker for people who might participate in any testing effort.

I used d-installer-live.x86_64-0.4.2-Build2.8.iso and selected Leap 15.4 installation with Czech localization.
Installation went fine (wizzard was still in English, I suppose that this is expected ad this phase of development)

I received error message that localization files are not available after reboot to freshly installed "minimal" environment. I expect that minimal is the reason behind the issue here.

![d-installer-locale](https://user-images.githubusercontent.com/510119/198052777-7828c1ca-fa89-4d7d-a68b-3a3cfdb84fb8.png)

**Comment by imobachgs** [comment] 2022-10-26 21:21
Thanks for the report. Yes, we are installing just a minimal set of packages, but it is good to have an issue to track (and solve) this problem.

**Comment by 4sokol** [comment] 2022-11-04 21:43
having the same issue
![locale](https://user-images.githubusercontent.com/72856789/200079371-ed0bab2f-51a0-4e33-a341-57d8c5a2ea69.png)

**Comment by mchf** [comment] 2023-03-03 10:21
Cannot reproduce in (several) latest builds see
![dinstaller_locale_2](https://user-images.githubusercontent.com/1579239/222695425-b41cdbf4-75d3-4c26-a291-0fd9449b7425.png)
So closing for now.

**Closed by mchf** 2023-03-03 10:21 UTC
Labels: bug, enhancement
